#cloud-config

## TEMAPLATE FILE FOR POPULATING USER-DATA
##
## VARIABLES
## - ADMIN_USER=
## - SSH_PUBLIC_KEY=
## - HOST=
## - STATIC_IP=

---

##
## Manage users and groups
##
chpasswd:
  expire: false
  list:
    - ${ADMIN_USER}:${ADMIN_USER}

users:
  - name: ${ADMIN_USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
    - "${SSH_PUBLIC_KEY}"

##
## Install or update packages
##
packages:
  - apt-transport-https
  - avahi-daemon
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
package_update: true
package_upgrade: true
package_reboot_if_required: true

##
## Configure hostname
##
preserve_hostname: false
fqdn: ${HOST}.local
hostname: ${HOST}

##
## Write out configuration files
##
write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",    
          "max-file": "3"    
        }
      }

##
## Install Docker, force netplan and turn swapoff
##
runcmd:
  - swapoff -a
  - curl -fsSL https://get.docker.com | bash
  - usermod -aG docker ${ADMIN_USER}

final_message: "The system is finally up after $UPTIME seconds"
